alliancedigitale/src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CalendarRepository::class)]
class Calendar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $all_day = null;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isValidated = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function isIsValidated(): ?bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(?bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }
}

alliancedigitale/src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Calendar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // ->add('title')
            // ->add('start', DateTimeType::class, [
            //     'date_widget' => 'single_text',
            // ])
            // ->add('end', DateTimeType::class, [
            //     'date_widget' => 'single_text',
            // ])
            
            // ->add('all_day')
            ->add('background_color', ChoiceType::class, [
                'label' => 'Background Color',
                'choices' => [
                    'Tâche effectuée (verte)' => '#28a745',
                    'Tâche à faire (rouge)' => '#dc3545'
                    
                ],
            ])
            ->add('isValidated', ChoiceType::class, [
                'choices' => [
                    'Oui' => true,
                    'Non' => false,
                ],
                'expanded' => true, 
                'multiple' => false, 
            ])
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}

alliancedigitale/src/Controller/CalendarController.php
<?php

namespace App\Controller;

use App\Entity\Calendar;
use App\Form\CalendarType;
use App\Repository\CalendarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/calendar')]
class CalendarController extends AbstractController
{
    #[Route('/', name: 'app_calendar_index', methods: ['GET'])]
    public function index(CalendarRepository $calendarRepository): Response
    {
        return $this->render('calendar/index.html.twig', [
            'calendars' => $calendarRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_calendar_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CalendarRepository $calendarRepository): Response
    {
        $calendar = new Calendar();
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $calendarRepository->save($calendar, true);

            return $this->redirectToRoute('app_calendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('calendar/new.html.twig', [
            'calendar' => $calendar,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_calendar_show', methods: ['GET'])]
    public function show(Calendar $calendar): Response
    {
        return $this->render('calendar/show.html.twig', [
            'calendar' => $calendar,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_calendar_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Calendar $calendar, CalendarRepository $calendarRepository): Response
    {
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $calendarRepository->save($calendar, true);

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('calendar/edit.html.twig', [
            'calendar' => $calendar,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_calendar_delete', methods: ['POST'])]
    public function delete(Request $request, Calendar $calendar, CalendarRepository $calendarRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$calendar->getId(), $request->request->get('_token'))) {
            $calendarRepository->remove($calendar, true);
        }

        return $this->redirectToRoute('app_calendar_index', [], Response::HTTP_SEE_OTHER);
    }
 }

alliancedigitale/templates/calendar/_delete_form.html.twig
<form method="post" action="{{ path('app_calendar_delete', {'id': calendar.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ calendar.id) }}">
    <button class="btn">Delete</button>
</form>

alliancedigitale/templates/calendar/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

alliancedigitale/templates/calendar/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un événement{% endblock %}


{% block body %}
    {{include("navbar.html.twig")}}

       
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');



.backgroundimg{
    background-size: cover;
}

.logoalliance{
  width:15rem;
}

.bcggrey{
  background-color:#535353;
  width:100%;
  padding: 3rem 0 !important;
  display: flex;
  justify-content: center;
}

.text-bg-warning{
  background-color:#ea5b0c !important;
}

.hoverbtn:hover{
  background-color:#535353 !important;
}

.mdpforgotten{
  color:#ea5b0c;
  text-decoration: none;
  font-style:italic !important;
}

.mdpforgotten:hover{
  color:#313635;
}

.bargrey{
    width:100%;
    height:1px;
    background-color:grey;
    opacity:0.4;
    margin-bottom:20px;
}

</style>


    <section class="vh-100 bg-image backgroundimg"
  style="background-image: url('https://thumbs.dreamstime.com/b/orange-gradient-background-modern-clean-background-copy-space-blank-background-design-cover-power-point-banner-181589490.jpg');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body px-5 py-2">
              <h2 class=" text-center my-5"><i><strong>Modifier l'état de la tâche</strong></i></h2>
              <div class="bargrey"></div>

      
            
    <div class="card-body">
    {{ form_start(form) }}

    
    <div class="form-outline mb-4">
        {{ form_label(form.isValidated, "La tâche est-elle effectuée?", {'attr': {'class':'form-label'}}) }}
        {{ form_widget(form.isValidated, {'attr': {'class':'d-flex flex-column btn btn-outline-warning'}}) }}
        {{ form_errors(form.isValidated) }}
    </div>

    <div class="form-outline mb-4">
        {{ form_label(form.background_color, "Etat :", {'attr': {'class':'form-label'}}) }}
        {{ form_widget(form.background_color, {'attr': {'class':'form-control form-control-lg'}}) }}
        {{ form_errors(form.background_color) }}
    </div>

    <div class="form-outline mb-4">
        {{ form_label(form.description, "Description :", {'attr': {'class':'form-label'}}) }}
        {{ form_widget(form.description, {'attr': {'class':'form-control form-control-lg'}}) }}
        {{ form_errors(form.description) }}
    </div>

<div class="d-flex justify-content-center">
    <button class="btn btn-block btn-lg gradient-custom-4 px-5 text-light text-bg-warning mt-4 hoverbtn" type="submit">
        Valider
    </button>
    </div>
        {{ form_end(form) }}
            </div>
        </div>
    
    <div class="bcggrey px-2 pt-2 mt-5">
    <img class="logoalliance btn mx-3" src="https://alliance-digital.fr/wp-content/uploads/2021/09/Alliance-Digital-Logo-teste-2-2048x355.png">
    </div>
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

alliancedigitale/templates/calendar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendar index{% endblock %}

{% block body %}
    <h1>Calendar index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Start</th>
                <th>End</th>
                <th>Description</th>
                <th>All_day</th>
                <th>Background_color</th>
                <th>isValidated</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for calendar in calendars %}
            <tr>
                <td>{{ calendar.id }}</td>
                <td>{{ calendar.title }}</td>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.description }}</td>
                <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td>
                <td>{{ calendar.backgroundColor }}</td>
                <td>{{ calendar.isValidated ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_calendar_show', {'id': calendar.id}) }}">show</a>
                    <a href="{{ path('app_calendar_edit', {'id': calendar.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_calendar_new') }}">Create new</a>
{% endblock %}

alliancedigitale/templates/calendar/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Calendar{% endblock %}

{% block body %}
    <h1>Create new Calendar</h1>

    {{ include('calendar/_form.html.twig') }}

    <a href="{{ path('app_calendar_index') }}">back to list</a>
{% endblock %}

alliancedigitale/templates/calendar/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendar{% endblock %}

{% block body %}
    <h1>Calendar</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ calendar.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ calendar.title }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ calendar.description }}</td>
            </tr>
            <tr>
                <th>All_day</th>
                <td>{{ calendar.allDay ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ calendar.backgroundColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_calendar_index') }}">back to list</a>

    <a href="{{ path('app_calendar_edit', {'id': calendar.id}) }}">edit</a>

    {{ include('calendar/_delete_form.html.twig') }}
{% endblock %}